class Languages:
    JS = ['js']
    JSX = ['jsx']
    JAVA = ['java']
    PYTHON = ['py']
    C = ['c']
    CPP = ['cpp']
    CSHARP = ['cs']
    RUBY = ['rb']
    GO = ['go']
    SWIFT = ['swift']
    KOTLIN = ['kt', 'kts']
    PHP = ['php']
    HTML = ['html']
    CSS = ['css']
    SCSS = ['scss']
    LESS = ['less']
    SQL = ['sql']
    R = ['r']
    SHELL = ['sh']
    OBJECTIVE_C = ['m']
    PERL = ['pl']
    RUST = ['rs']
    DART = ['dart']
    COFFEE = ['coffee']
    SCALA = ['scala']
    HASKELL = ['hs']
    ERLANG = ['erl']
    CRYSTAL = ['cr']
    ELIXIR = ['ex']
    LISP = ['lisp']
    LUA = ['lua']
    VIM = ['vim']
    NIM = ['nim']
    PASCAL = ['pas']
    FORTH = ['forth']
    OCAML = ['ml']
    FSHARP = ['fs']
    JAVASCRIPT = ['js']
    TYPESCRIPT = ['ts']
    MARKDOWN = ['md']
    XML = ['xml']
    JSON = ['json']
    YAML = ['yaml']
    TOML = ['toml']
    HAML = ['haml']
    HANDLEBARS = ['hbs']
    JADE = ['jade']
    SLIM = ['slim']
    EJS = ['ejs']
    RAZOR = ['cshtml']

    @staticmethod
    def get_languages(languages):
        return [getattr(Languages, language) for language in languages]
